-- eyesclosed: a minimal low-chroma theme

vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end
vim.o.background = 'dark'
vim.o.termguicolors = true
vim.g.colors_name = 'eyesclosed'

local p = {
  night = "#111214",
  lid = "#1A1B21",
  shade = "#383B4A",
  glow = "#464957",
  haze = "#696D7D",
  ash = "#9A9DAE",
  mist = "#BBBCC7",
  moon = "#CDCFD1",
  tide = "#779BB0",
  frost = "#B7C8CB",
  blush = "#D8D0D0",
  linen = "#D9CBAE",
  candle = "#ECD8AE",
  ember = "#C18E5F",
  flare = "#FFABA2",
}

local hl = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end

hl("Normal", { fg = p.mist, bg = p.night })
hl("NormalFloat", { fg = p.mist, bg = p.lid })
hl("FloatBorder", { fg = p.shade, bg = p.lid })
hl("FloatTitle", { fg = p.ash, bg = p.lid })
hl("NormalNC", { fg = p.mist, bg = p.night })
hl("Cursor", { fg = p.night, bg = p.moon })
hl("lCursor", { fg = p.night, bg = p.moon })
hl("TermCursor", { fg = p.night, bg = p.moon })
hl("CursorLine", { bg = p.lid })
hl("CursorColumn", { bg = p.lid })
hl("ColorColumn", { bg = p.lid })
hl("CursorLineNr", { fg = p.ash, bold = true })
hl("LineNr", { fg = p.shade })
hl("SignColumn", { bg = p.night })
hl("FoldColumn", { fg = p.shade })
hl("Folded", { fg = p.ash, bg = p.lid })
hl("Visual", { bg = p.shade })
hl("VisualNOS", { bg = p.shade })
hl("Search", { fg = p.mist, bg = p.glow })
hl("CurSearch", { fg = p.night, bg = p.candle })
hl("IncSearch", { fg = p.night, bg = p.candle })
hl("Substitute", { fg = p.night, bg = p.candle })
hl("MatchParen", { fg = p.moon, bg = p.lid, bold = true })
hl("Pmenu", { fg = p.mist, bg = p.lid })
hl("PmenuSel", { fg = p.moon, bg = p.glow, bold = true })
hl("PmenuSbar", { bg = p.lid })
hl("PmenuThumb", { bg = p.shade })
hl("PmenuMatch", { fg = p.candle, bg = p.lid })
hl("PmenuMatchSel", { fg = p.candle, bg = p.glow, bold = true })
hl("StatusLine", { fg = p.ash, bg = p.lid })
hl("StatusLineNC", { fg = p.haze, bg = p.lid })
hl("TabLine", { fg = p.haze, bg = p.lid })
hl("TabLineFill", { bg = p.lid })
hl("TabLineSel", { fg = p.mist, bg = p.night, bold = true })
hl("WinSeparator", { fg = p.shade })
hl("VertSplit", { fg = p.shade })
hl("WinBar", { fg = p.ash })
hl("WinBarNC", { fg = p.haze })
hl("NonText", { fg = p.shade })
hl("Whitespace", { fg = p.shade })
hl("SpecialKey", { fg = p.shade })
hl("EndOfBuffer", { fg = p.night })
hl("Conceal", { fg = p.haze })
hl("Directory", { fg = p.frost, bold = true })
hl("Title", { fg = p.moon, bold = true })
hl("ErrorMsg", { fg = p.flare, bold = true })
hl("WarningMsg", { fg = p.ember, bold = true })
hl("MoreMsg", { fg = p.tide })
hl("ModeMsg", { fg = p.ash, bold = true })
hl("Question", { fg = p.tide })
hl("QuickFixLine", { bg = p.lid })
hl("WildMenu", { fg = p.moon, bg = p.glow })
hl("Underlined", { fg = p.frost, underline = true })
hl("SpellBad", { sp = p.flare, undercurl = true })
hl("SpellCap", { sp = p.ember, underdashed = true })
hl("SpellRare", { sp = p.tide, underdotted = true })
hl("SpellLocal", { sp = p.haze, underdotted = true })
hl("Comment", { fg = p.haze, italic = true })
hl("Constant", { fg = p.candle })
hl("String", { fg = p.linen })
hl("Character", { fg = p.linen })
hl("Number", { fg = p.candle })
hl("Boolean", { fg = p.candle })
hl("Float", { fg = p.candle })
hl("Identifier", { fg = p.mist })
hl("Function", { fg = p.blush })
hl("Statement", { fg = p.tide, bold = true })
hl("Conditional", { fg = p.tide, bold = true })
hl("Repeat", { fg = p.tide, bold = true })
hl("Label", { fg = p.mist, italic = true })
hl("Operator", { fg = p.ash })
hl("Keyword", { fg = p.tide, bold = true })
hl("Exception", { fg = p.tide, bold = true })
hl("PreProc", { fg = p.ash })
hl("Include", { fg = p.tide, bold = true })
hl("Define", { fg = p.ash })
hl("Macro", { fg = p.frost, italic = true })
hl("PreCondit", { fg = p.ash })
hl("Type", { fg = p.frost })
hl("StorageClass", { fg = p.tide, bold = true })
hl("Structure", { fg = p.tide, bold = true })
hl("Typedef", { fg = p.tide, bold = true })
hl("Special", { fg = p.ash })
hl("SpecialChar", { fg = p.candle, bold = true })
hl("Tag", { fg = p.tide })
hl("Delimiter", { fg = p.haze })
hl("SpecialComment", { fg = p.ash, italic = true })
hl("Debug", { fg = p.ember })
hl("Error", { fg = p.flare, bold = true })
hl("Todo", { fg = p.candle, bold = true })
hl("Added", { fg = p.tide })
hl("Changed", { fg = p.ash })
hl("Removed", { fg = p.ember })
hl("DiffAdd", { bg = p.lid })
hl("DiffChange", { bg = p.lid })
hl("DiffDelete", { fg = p.haze, bg = p.night })
hl("DiffText", { bg = p.shade })
hl("diffAdded", { fg = p.tide })
hl("diffRemoved", { fg = p.ember })
hl("diffChanged", { fg = p.ash })
hl("diffFile", { fg = p.moon, bold = true })
hl("diffLine", { fg = p.haze })
hl("diffIndexLine", { fg = p.haze })
hl("DiagnosticError", { fg = p.flare, bold = true })
hl("DiagnosticUnderlineError", { sp = p.flare, undercurl = true })
hl("DiagnosticVirtualTextError", { fg = p.flare, bold = true })
hl("DiagnosticVirtualLinesError", { fg = p.flare, bold = true })
hl("DiagnosticFloatingError", { fg = p.flare, bg = p.lid })
hl("DiagnosticSignError", { fg = p.flare })
hl("DiagnosticWarn", { fg = p.ember, bold = true })
hl("DiagnosticUnderlineWarn", { sp = p.ember, underdashed = true })
hl("DiagnosticVirtualTextWarn", { fg = p.ember, bold = true })
hl("DiagnosticVirtualLinesWarn", { fg = p.ember, bold = true })
hl("DiagnosticFloatingWarn", { fg = p.ember, bg = p.lid })
hl("DiagnosticSignWarn", { fg = p.ember })
hl("DiagnosticInfo", { fg = p.tide, bold = true })
hl("DiagnosticUnderlineInfo", { sp = p.tide, underdotted = true })
hl("DiagnosticVirtualTextInfo", { fg = p.tide, bold = true })
hl("DiagnosticVirtualLinesInfo", { fg = p.tide, bold = true })
hl("DiagnosticFloatingInfo", { fg = p.tide, bg = p.lid })
hl("DiagnosticSignInfo", { fg = p.tide })
hl("DiagnosticHint", { fg = p.haze, bold = true })
hl("DiagnosticUnderlineHint", { sp = p.haze, underdotted = true })
hl("DiagnosticVirtualTextHint", { fg = p.haze, bold = true })
hl("DiagnosticVirtualLinesHint", { fg = p.haze, bold = true })
hl("DiagnosticFloatingHint", { fg = p.haze, bg = p.lid })
hl("DiagnosticSignHint", { fg = p.haze })
hl("DiagnosticOk", { fg = p.tide, bold = true })
hl("DiagnosticUnderlineOk", { sp = p.tide, underdotted = true })
hl("DiagnosticVirtualTextOk", { fg = p.tide, bold = true })
hl("DiagnosticVirtualLinesOk", { fg = p.tide, bold = true })
hl("DiagnosticFloatingOk", { fg = p.tide, bg = p.lid })
hl("DiagnosticSignOk", { fg = p.tide })
hl("DiagnosticUnnecessary", { fg = p.haze })
hl("DiagnosticDeprecated", { fg = p.haze, strikethrough = true })
hl("LspInlayHint", { fg = p.haze, italic = true })
hl("LspReferenceText", { bg = p.lid })
hl("LspReferenceRead", { bg = p.lid })
hl("LspReferenceWrite", { bg = p.shade })
hl("LspSignatureActiveParameter", { fg = p.candle, bold = true })
hl("@variable", { fg = p.mist })
hl("@variable.parameter", { fg = p.mist })
hl("@variable.member", { fg = p.ash })
hl("@variable.builtin", { fg = p.tide, italic = true })
hl("@property", { fg = p.ash })
hl("@constant", { fg = p.candle })
hl("@constant.builtin", { fg = p.candle })
hl("@constant.macro", { fg = p.candle })
hl("@module", { fg = p.ash })
hl("@module.builtin", { fg = p.ash })
hl("@label", { fg = p.mist, italic = true })
hl("@string", { fg = p.linen })
hl("@string.documentation", { fg = p.ash, italic = true })
hl("@string.escape", { fg = p.candle, bold = true })
hl("@string.regexp", { fg = p.candle })
hl("@string.special", { fg = p.candle })
hl("@string.special.url", { fg = p.frost, underline = true })
hl("@character", { fg = p.linen })
hl("@character.special", { fg = p.candle, bold = true })
hl("@number", { fg = p.candle })
hl("@number.float", { fg = p.candle })
hl("@boolean", { fg = p.candle })
hl("@type", { fg = p.frost })
hl("@type.builtin", { fg = p.ash })
hl("@type.definition", { fg = p.frost })
hl("@attribute", { fg = p.ash })
hl("@attribute.builtin", { fg = p.ash })
hl("@function", { fg = p.blush })
hl("@function.builtin", { fg = p.blush })
hl("@function.call", { fg = p.blush })
hl("@function.macro", { fg = p.frost, italic = true })
hl("@function.method", { fg = p.blush })
hl("@function.method.call", { fg = p.blush })
hl("@constructor", { fg = p.frost })
hl("@operator", { fg = p.ash })
hl("@keyword", { fg = p.tide, bold = true })
hl("@keyword.coroutine", { fg = p.tide, bold = true })
hl("@keyword.function", { fg = p.tide, bold = true })
hl("@keyword.operator", { fg = p.tide, bold = true })
hl("@keyword.import", { fg = p.tide, bold = true })
hl("@keyword.type", { fg = p.tide, bold = true })
hl("@keyword.modifier", { fg = p.tide, bold = true })
hl("@keyword.repeat", { fg = p.tide, bold = true })
hl("@keyword.return", { fg = p.tide, bold = true })
hl("@keyword.exception", { fg = p.tide, bold = true })
hl("@keyword.conditional", { fg = p.tide, bold = true })
hl("@keyword.directive", { fg = p.ash })
hl("@punctuation.delimiter", { fg = p.haze })
hl("@punctuation.bracket", { fg = p.haze })
hl("@punctuation.special", { fg = p.ash })
hl("@comment", { fg = p.haze, italic = true })
hl("@comment.documentation", { fg = p.ash, italic = true })
hl("@comment.error", { fg = p.flare, bold = true })
hl("@comment.warning", { fg = p.ember, bold = true })
hl("@comment.todo", { fg = p.candle, bold = true })
hl("@comment.note", { fg = p.tide, bold = true })
hl("@markup.strong", { fg = p.moon, bold = true })
hl("@markup.italic", { fg = p.mist, italic = true })
hl("@markup.strikethrough", { fg = p.haze, strikethrough = true })
hl("@markup.underline", { fg = p.mist, underline = true })
hl("@markup.heading", { fg = p.moon, bold = true })
hl("@markup.quote", { fg = p.ash, italic = true })
hl("@markup.math", { fg = p.candle })
hl("@markup.link", { fg = p.frost })
hl("@markup.link.label", { fg = p.frost, underline = true })
hl("@markup.link.url", { fg = p.haze })
hl("@markup.raw", { fg = p.linen })
hl("@markup.list", { fg = p.tide })
hl("@markup.list.checked", { fg = p.tide })
hl("@markup.list.unchecked", { fg = p.haze })
hl("@diff.plus", { fg = p.tide })
hl("@diff.minus", { fg = p.ember })
hl("@diff.delta", { fg = p.ash })
hl("@tag", { fg = p.tide })
hl("@tag.builtin", { fg = p.tide })
hl("@tag.attribute", { fg = p.ash })
hl("@tag.delimiter", { fg = p.haze })
hl("@lsp.type.parameter", { fg = p.mist })
hl("@lsp.type.property", { fg = p.ash })
hl("@lsp.type.namespace", { fg = p.ash })
hl("@lsp.type.macro", { fg = p.frost, italic = true })
hl("@lsp.type.enumMember", { fg = p.frost })
hl("@lsp.type.typeParameter", { fg = p.frost })
hl("@lsp.type.builtinType", { fg = p.ash })
hl("@lsp.type.selfKeyword", { fg = p.tide, italic = true })
hl("@lsp.type.lifetime", { fg = p.mist, italic = true })
hl("@lsp.mod.documentation", { fg = p.ash, italic = true })
hl("GitSignsAdd", { fg = p.tide })
hl("GitSignsChange", { fg = p.haze })
hl("GitSignsDelete", { fg = p.ember })
hl("TelescopeBorder", { fg = p.shade, bg = p.lid })
hl("TelescopeNormal", { fg = p.mist, bg = p.lid })
hl("TelescopeSelection", { fg = p.moon, bg = p.glow })
hl("TelescopeMatching", { fg = p.candle, bold = true })
hl("TelescopePromptPrefix", { fg = p.tide })

vim.g.terminal_color_0 = p.shade
vim.g.terminal_color_1 = p.flare
vim.g.terminal_color_2 = p.tide
vim.g.terminal_color_3 = p.candle
vim.g.terminal_color_4 = p.frost
vim.g.terminal_color_5 = p.ash
vim.g.terminal_color_6 = p.blush
vim.g.terminal_color_7 = p.mist
vim.g.terminal_color_8 = p.haze
vim.g.terminal_color_9 = p.flare
vim.g.terminal_color_10 = p.tide
vim.g.terminal_color_11 = p.candle
vim.g.terminal_color_12 = p.frost
vim.g.terminal_color_13 = p.ash
vim.g.terminal_color_14 = p.blush
vim.g.terminal_color_15 = p.moon
