# eyesclosed: a minimal low-chroma theme

theme[main_bg]="#0B0D0E"

theme[main_fg]="#B7B8C4"

theme[title]="#D3CEE4"

theme[hi_fg]="#EAD3A5"

theme[selected_bg]="#404451"

theme[selected_fg]="#E4E5ED"

theme[inactive_fg]="#4E505F"

theme[graph_text]="#9496A8"

theme[proc_misc]="#7498AE"

theme[cpu_box]="#393B48"
theme[mem_box]="#393B48"
theme[net_box]="#393B48"
theme[proc_box]="#393B48"

theme[div_line]="#323644"

theme[temp_start]="#5C7684"
theme[temp_mid]="#DCC396"
theme[temp_end]="#FFA59B"

theme[cpu_start]="#5C7684"
theme[cpu_mid]="#DCC396"
theme[cpu_end]="#FFA59B"

theme[free_start]="#5C7684"
theme[free_mid]="#99B3C0"
theme[free_end]="#B4CAD6"

theme[cached_start]="#58616E"
theme[cached_mid]="#8E84A6"
theme[cached_end]="#A9A0C1"

theme[available_start]="#5C7684"
theme[available_mid]="#99B3C0"
theme[available_end]="#B4CAD6"

theme[used_start]="#5C7684"
theme[used_mid]="#DCC396"
theme[used_end]="#FFA59B"

theme[download_start]="#5C7684"
theme[download_mid]="#99B3C0"
theme[download_end]="#B4CAD6"

theme[upload_start]="#8E625A"
theme[upload_mid]="#BF8A5A"
theme[upload_end]="#E8D3AD"

theme[process_start]="#5C7684"
theme[process_mid]="#DCC396"
theme[process_end]="#FFA59B"
