# eyesclosed: a low-chroma dark theme

theme[main_bg]="#111214"

theme[main_fg]="#BBBCC7"

theme[title]="#CDCFD1"

theme[hi_fg]="#ECD8AE"

theme[selected_bg]="#464957"

theme[selected_fg]="#CDCFD1"

theme[inactive_fg]="#696D7D"

theme[graph_text]="#9A9DAE"

theme[proc_misc]="#779BB0"

theme[cpu_box]="#383B4A"
theme[mem_box]="#383B4A"
theme[net_box]="#383B4A"
theme[proc_box]="#383B4A"

theme[div_line]="#383B4A"

theme[temp_start]="#779BB0"
theme[temp_mid]="#ECD8AE"
theme[temp_end]="#FFABA2"

theme[cpu_start]="#779BB0"
theme[cpu_mid]="#ECD8AE"
theme[cpu_end]="#FFABA2"

theme[free_start]="#779BB0"
theme[free_mid]="#B7C8CB"
theme[free_end]="#B7C8CB"

theme[cached_start]="#696D7D"
theme[cached_mid]="#9A9DAE"
theme[cached_end]="#9A9DAE"

theme[available_start]="#779BB0"
theme[available_mid]="#B7C8CB"
theme[available_end]="#B7C8CB"

theme[used_start]="#779BB0"
theme[used_mid]="#ECD8AE"
theme[used_end]="#FFABA2"

theme[download_start]="#779BB0"
theme[download_mid]="#B7C8CB"
theme[download_end]="#B7C8CB"

theme[upload_start]="#C18E5F"
theme[upload_mid]="#C18E5F"
theme[upload_end]="#ECD8AE"

theme[process_start]="#779BB0"
theme[process_mid]="#ECD8AE"
theme[process_end]="#FFABA2"
