# eyesclosed: a minimal low-chroma theme

theme[main_bg]="#111214"

theme[main_fg]="#BBBCC7"

theme[title]="#D7D2E6"

theme[hi_fg]="#ECD8AE"

theme[selected_bg]="#464957"

theme[selected_fg]="#E9E9F0"

theme[inactive_fg]="#505261"

theme[graph_text]="#9799AA"

theme[proc_misc]="#779BB0"

theme[cpu_box]="#3B3D4A"
theme[mem_box]="#3B3D4A"
theme[net_box]="#3B3D4A"
theme[proc_box]="#3B3D4A"

theme[div_line]="#383B4A"

theme[temp_start]="#5F7986"
theme[temp_mid]="#DEC79C"
theme[temp_end]="#FFABA2"

theme[cpu_start]="#5F7986"
theme[cpu_mid]="#DEC79C"
theme[cpu_end]="#FFABA2"

theme[free_start]="#5F7986"
theme[free_mid]="#9EB6C3"
theme[free_end]="#B9CED9"

theme[cached_start]="#5B6370"
theme[cached_mid]="#9187A8"
theme[cached_end]="#ACA4C3"

theme[available_start]="#5F7986"
theme[available_mid]="#9EB6C3"
theme[available_end]="#B9CED9"

theme[used_start]="#5F7986"
theme[used_mid]="#DEC79C"
theme[used_end]="#FFABA2"

theme[download_start]="#5F7986"
theme[download_mid]="#9EB6C3"
theme[download_end]="#B9CED9"

theme[upload_start]="#90655D"
theme[upload_mid]="#C18E5F"
theme[upload_end]="#EAD8B6"

theme[process_start]="#5F7986"
theme[process_mid]="#DEC79C"
theme[process_end]="#FFABA2"
