# eyesclosed: a minimal low-chroma theme
# In kitty.conf:  include ~/dev/eyesclosed/themes/kitty/eyesclosed.conf

foreground              #BBBCC7
background              #111214
selection_foreground    none
selection_background    #383B4A
cursor                  #CDCFD1
cursor_text_color       #111214
url_color               #B7C8CB
active_border_color     #779BB0
inactive_border_color   #383B4A
bell_border_color       #ECD8AE
visual_bell_color       #1A1B21
active_tab_foreground   #CDCFD1
active_tab_background   #111214
active_tab_font_style   bold
inactive_tab_foreground #696D7D
inactive_tab_background #1A1B21
tab_bar_background      #1A1B21
mark1_foreground        #111214
mark1_background        #779BB0
mark2_foreground        #111214
mark2_background        #ECD8AE
mark3_foreground        #111214
mark3_background        #B7C8CB

color0                  #383B4A
color1                  #FFABA2
color2                  #779BB0
color3                  #ECD8AE
color4                  #B7C8CB
color5                  #9A9DAE
color6                  #D8D0D0
color7                  #BBBCC7
color8                  #696D7D
color9                  #FFABA2
color10                 #779BB0
color11                 #ECD8AE
color12                 #B7C8CB
color13                 #9A9DAE
color14                 #D8D0D0
color15                 #CDCFD1
